#! /bin/bash

root=$(pwd)
local_repo="${root}/local"

cd ${local_repo}

for pkg in $@
do
    :
    echo $(date +%s.%N) > ${local_repo}/${pkg}/.package
done;

git add .
git commit -m "Commit on $(date)"
